import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

class PDFService {
  async generateApplicantResume(data: any, fileName: string): Promise<string> {
    const uploadDir = path.join(process.cwd(), "uploads", "resumes");
    if (!fs.existsSync(uploadDir)) {
      fs.mkdirSync(uploadDir, { recursive: true });
    }

    const filePath = path.join(uploadDir, fileName);
    const doc = new PDFDocument({ margin: 50 });

    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // Header - Name and Headline
    doc.fillColor("#6366f1").fontSize(24).text(`${data.firstName || ""} ${data.lastName || ""}`.trim(), { align: "left" });
    doc.moveDown(0.2);
    doc.fillColor("#6b7280").fontSize(14).text(data.headline || "Technical Professional", { align: "left" });
    
    doc.moveDown(1);
    
    // Contact Info
    doc.fillColor("#000000").fontSize(10);
    doc.text(`Email: ${data.email || "N/A"}`, { align: "left" });
    doc.text(`Location: ${data.location || "N/A"}`, { align: "left" });
    
    if (data.socialLinks) {
      if (data.socialLinks.linkedin) doc.text(`LinkedIn: ${data.socialLinks.linkedin}`);
      if (data.socialLinks.github) doc.text(`GitHub: ${data.socialLinks.github}`);
    }

    doc.moveDown(1.5);
    doc.lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke("#e5e7eb");
    doc.moveDown(1.5);

    // Summary / Bio
    doc.fillColor("#6366f1").fontSize(16).text("Professional Summary", { underline: true });
    doc.moveDown(0.5);
    doc.fillColor("#374151").fontSize(11).text(data.bio || "No summary available.", { align: "justify", lineGap: 3 });

    doc.moveDown(1.5);

    // Skills
    if (data.skills && data.skills.length > 0) {
      doc.fillColor("#6366f1").fontSize(16).text("Core Technical Skills", { underline: true });
      doc.moveDown(0.5);
      const skillsText = data.skills.map((s: any) => `${s.name} (${s.level || "Intermediate"})`).join(", ");
      doc.fillColor("#374151").fontSize(11).text(skillsText);
      doc.moveDown(1.5);
    }

    // Work Experience
    if (data.workExperience && data.workExperience.length > 0) {
      doc.fillColor("#6366f1").fontSize(16).text("Work Experience", { underline: true });
      doc.moveDown(0.5);
      
      data.workExperience.forEach((exp: any) => {
        doc.fillColor("#111827").fontSize(12).text(`${exp.role} at ${exp.company}`, { bold: true });
        doc.fillColor("#6b7280").fontSize(10).text(`${exp.startDate} - ${exp.endDate || "Present"}`);
        doc.moveDown(0.2);
        doc.fillColor("#374151").fontSize(10).text(exp.description || "", { align: "justify" });
        doc.moveDown(0.8);
      });
      doc.moveDown(1);
    }

    // Education
    if (data.education && data.education.length > 0) {
      doc.fillColor("#6366f1").fontSize(16).text("Education", { underline: true });
      doc.moveDown(0.5);
      
      data.education.forEach((edu: any) => {
        doc.fillColor("#111827").fontSize(12).text(`${edu.degree} in ${edu.fieldOfStudy}`);
        doc.fillColor("#6b7280").fontSize(10).text(`${edu.institution} | ${edu.startYear} - ${edu.endYear}`);
        doc.moveDown(0.5);
      });
    }

    // Footer
    const pageCount = doc.bufferedPageRange().count;
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i);
      doc.fillColor("#9ca3af").fontSize(8).text(
        `Generated by Scrutiq AI Technical Portal - ${new Date().toLocaleDateString()}`,
        50,
        750,
        { align: "center" }
      );
    }

    doc.end();

    return new Promise((resolve, reject) => {
      stream.on("finish", () => resolve(`resumes/${fileName}`));
      stream.on("error", reject);
    });
  }
}

export default new PDFService();
